version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - server
    networks:
      - app-network
    environment:
      - SERVER_ADDR=server:8080  # Use container name as hostname

networks:
  app-network:
    driver: bridge 